### ISSUE TITLE
Problem with persisting filter selections

### ISSUE THREAD

**Issue by goldmerc** [optimistdigital/nova-detached-filters#4] opened 2020-10-28 15:03 UTC
2 issues - 

1. If I select some filters and then click the lock to turn it green, the filters selected before the lock is turned green are not persisted. I think from a user perspective, the expected behavior would be that after selecting filters, if the lock is turned on, those filters already selected should be persisted.

2. If I turn on persisting and select some filters, then I navigate away from the page and come back, the filter card shows the correct filters selected but the index component does not show the correct filtered list of items. If I refresh the page, it works. What appears to be happening is that the correct items are shown for a moment and then the unfiltered list of items is loaded in over them. Interestingly the built in drop down filter shows the right number of filters and the page count at the bottom of the page, shows the right total, so I see something like '1-25 of 8'.

**Comment by KasparRosin** [comment] 2020-10-29 10:54
I was unable to reproduce the 1st issue. Could you reopen it in a new issue, so i can close this one?.

The 2nd issue was fixed and is included in [1.0.6](https://github.com/optimistdigital/nova-detached-filters/releases/tag/1.0.6). Thank you very much!

**Closed by KasparRosin** 2020-10-29 10:54 UTC

**Comment by goldmerc** [comment] 2020-10-30 18:01
Both issues have resolved for me now. Thanks!
